### ISSUE TITLE
[FEATURE REQ] Audio/Video multitracks synch by audio aligning

### ISSUE THREAD

**Issue by MarcoRavich** [smallstepforman/Medo#15]
It would be really cool - and almost uniqe, at least between open source NLEs - to have an automatic integrated function that helps (multicam, expecially) editors to have synched multitracks in a snap.

I found some interesting resources that may help to integrate it:
- https://github.com/protyposis/AudioAlign - a tool written for research purposes to automatically synchronize audio and video recordings that have either been recorded in parallel at the same event or contain the same aural information.
- https://github.com/alopatindev/sync-audio-tracks - a tool (based on [Miles McCoo's cross-correlation implementation](https://web.archive.org/web/20170916044116/https://nerd.mmccoo.com/2017/06/19/automatically-aligning-multiple-videoaudio-clips-in-kdenlive/)) that calculates a delay between two audios and produces a shifted audio.
- https://github.com/benfmiller/audalign - Python package for aligning audio files using audio fingerprinting.
- https://github.com/recastrodiaz/align-audio-recordings-julia - Aligning video recordings with Julia

Hope that inspires.

**Comment by smallstepforman** [comment]
Thank you of your feedback.  Some of the professional NLE do offer this feature, and eventually Medo might get it as well (sync via audio analysis).  A feature for R2 perhaps where we could target more professional use cases ...
I will close this issue for R1 though.
