### ISSUE TITLE
Settings are not saved?

### ISSUE THREAD

**Issue by ahwayakchih** [smallstepforman/Medo#2]
Hi,

First of all, thanks for creating and open-sourcing this project!

I built it using cmake+make. When i launch it and try to switch theme from settings window, "restart" button shows up. Application exits when i click it, but does not restart. After i restart it manually, nothing seems to be changed and settings window shows "dark" theme as "selected". Same happens if i change selected theme, close settings window and close application myself.

One thing i did not try (yet) is to build package, install it and then try switching settings. Should i do that, or it wouldn't make a difference?

**Comment by smallstepforman** [comment]
Thanks ahwayakchih.  That is a valid bug, what is missing is a directory called ~/config/settings/Medo   On my development box I always had that directory so saving always worked.  The software fails to create the directory if it doesn't exist.  A quick fix is to manually create the directory ~/config/settings/Medo, and after that saving will work.
I will fix this in the next couple of days.  Thank you for the bug report and for taking the time to try out the application

**Comment by ahwayakchih** [comment]
Thanks :). Creating `~/config/settings/Medo` folder fixed saving settings. But "restart" button only quits application and it needs to be started manually.

**Comment by Briseur** [comment]
Maybe folders /home/config/settings/Medo , /home/config/settings/Medo/Addons and  /home/config/settings/Medo/Plugins should be created at first start if  they don't exist already?

**Comment by smallstepforman** [comment]
Latest commit will check if home/config/settings/Medo directory exists, and create it if its missing.

ahwayakchih, ideally changes should be live and not require a restart button :)  To implement this, I'd either have to broadcast a change to all views (lots of code), or alternatively destroy all the windows and recreate them, this way the new settings would be picked up in the constructors.  This will happen in a future update, but for now I temporarily added the restart button to hint as to why the changes didn't take effect immediately.  

Briseur, thats a valid suggestion and may avoid confusion for some users.  I initially expected plugin/addon developers to take care of this.  If more developers/users mention this, I'll add this check to startup.  I come from old school spinning floppy disk background (even tape decks with C64) where every scan was not only time/CPU expensive, but loud :)
