### ISSUE TITLE
[SUGGESTION] (FFMPEG) color space "legalization"

### ISSUE THREAD

**Issue by MarcoRavich** [smallstepforman/Medo#20]
This feature helps all videomakers to "legalize" color space (recorded by their cameras) for broadcast standard.

All started from [this discussion](https://video.stackexchange.com/questions/29699/canon-rgb-color-space-shift-to-broadcast-range-with-ffmpeg) started by me for solving the problem with "Canon HF100 colorspace".

After evaluating a clip, [Gyan](https://video.stackexchange.com/users/1871/gyan) (an FFMPEG maintainer) suggested me:

> You can use the geq filter to remap the pixel value ranges.
>
> `ffmpeg`
> `-i input`
> `-vf "geq=lum='(p(X,Y)-16)/(255-16)*(235-16)+16':cb='(p(X,Y)-16)/(255-16)*(240-16)+16'"`
> `-c:v libx264 -c:a copy out.mp4`
>
>The geq filter rescales the input luma from 16-255 to 16-235, and both the input chroma from 16-255 to 16-240, which is the legal range for broadcast 8-bit signals.

Hope that inspires !

**Comment by smallstepforman** [comment]
Thanks forart for the feedback.  On my TODO list is creating a set of plugins to do colour space conversion (eg. Gamma to linear, SRGB to unorm, BT702 to BT2020 etc) and their inverses.  This is quite easy to do with GLSL shader plugins so shouldn't take more than 30min-1hour per converter.
Likewise, special converters per camera can also be made. 

Other than GLSL type plugins (the easier option), Medo can also import Adobe LUT files, I'm sure there is already a LUT for all these colour spaces which we can also reuse.  I'll see about finding some which I can legally distribute.
