### ISSUE TITLE
Commit history?

### ISSUE THREAD

**Issue by diversys** [smallstepforman/Medo#6]
It might be useful to recreate the repo to preserve commit history.

**Comment by smallstepforman** [comment]
Hi diversys.
I've just started using github (I'm traditionally a Mercurial user), so I'm not exactly sure what you mean?

**Comment by diversys** [comment]
I mean it would've been useful to migrate commit history from svn to git :)

**Comment by smallstepforman** [comment]
Hi diversys.  Even though I do have an archive of older versions during the project development (I wanted to create a timeline video), I honestly doubt the history is of any value to the community.  History begins with R1 beta 1 :)  Happy holidays.
